services:
  location-service:
    build:
      context: ..
      dockerfile: ./location-service/Dockerfile
      target: dev 
    container_name: location-service
    ports:
      - "9000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/location-service
      - /location-service/app/models
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  location-service-test:
    build:
      context: ..
      dockerfile: ./location-service/Dockerfile
      target: test
    container_name: location-service-test
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RIDER_PASSWORD_1: ${RIDER_PASSWORD_1}
      RIDER_PASSWORD_2: ${RIDER_PASSWORD_2}
      DRIVER_PASSWORD_1: ${DRIVER_PASSWORD_1}
      DRIVER_PASSWORD_2: ${DRIVER_PASSWORD_2}

    volumes:
      - /location-service/app/models
      - /location-service/tests
      - ./:/location-service 
    command: >
      sh -c "pytest -v --cov=app --cov-report=xml:coverage.xml tests/unittest &&
           sed -i 's|/location-service/app|location-service/app|g' coverage.xml"