# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${VITE_PORT}:${VITE_PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev