"""Modify field properties for EngagedDriver table

Revision ID: 2e3c0b1700f4
Revises: 9522af365d29
Create Date: 2025-03-12 17:44:58.291448

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2e3c0b1700f4'
down_revision = '9522af365d29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engageddriver', 'driver_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engageddriver', 'driver_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
