"""Added ON DELETE CASCADE for foreign keys

Revision ID: 810d3cae3574
Revises: 1c6c9a94b771
Create Date: 2025-01-31 02:24:31.814049

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '810d3cae3574'
down_revision = '1c6c9a94b771'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_driverlocation_socket_id', table_name='driverlocation')
    op.drop_constraint('driverlocation_driver_id_fkey', 'driverlocation', type_='foreignkey')
    op.create_foreign_key(None, 'driverlocation', 'driver', ['driver_id'], ['driver_id'], ondelete='CASCADE')
    op.drop_column('driverlocation', 'socket_id')
    op.alter_column('engageddriver', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('engageddriver_driver_id_fkey', 'engageddriver', type_='foreignkey')
    op.drop_constraint('engageddriver_req_id_fkey', 'engageddriver', type_='foreignkey')
    op.create_foreign_key(None, 'engageddriver', 'driver', ['driver_id'], ['driver_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'engageddriver', 'triprequest', ['req_id'], ['req_id'], ondelete='CASCADE')
    op.alter_column('rider', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('trip_rider_id_fkey', 'trip', type_='foreignkey')
    op.drop_constraint('trip_driver_id_fkey', 'trip', type_='foreignkey')
    op.alter_column('triprequest', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('triprequest_rider_id_fkey', 'triprequest', type_='foreignkey')
    op.create_foreign_key(None, 'triprequest', 'rider', ['rider_id'], ['rider_id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'triprequest', type_='foreignkey')
    op.create_foreign_key('triprequest_rider_id_fkey', 'triprequest', 'rider', ['rider_id'], ['rider_id'])
    op.alter_column('triprequest', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('trip_driver_id_fkey', 'trip', 'driver', ['driver_id'], ['driver_id'])
    op.create_foreign_key('trip_rider_id_fkey', 'trip', 'rider', ['rider_id'], ['rider_id'])
    op.alter_column('rider', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'engageddriver', type_='foreignkey')
    op.drop_constraint(None, 'engageddriver', type_='foreignkey')
    op.create_foreign_key('engageddriver_req_id_fkey', 'engageddriver', 'triprequest', ['req_id'], ['req_id'])
    op.create_foreign_key('engageddriver_driver_id_fkey', 'engageddriver', 'driver', ['driver_id'], ['driver_id'])
    op.alter_column('engageddriver', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('driverlocation', sa.Column('socket_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'driverlocation', type_='foreignkey')
    op.create_foreign_key('driverlocation_driver_id_fkey', 'driverlocation', 'driver', ['driver_id'], ['driver_id'])
    op.create_index('ix_driverlocation_socket_id', 'driverlocation', ['socket_id'], unique=False)
    op.alter_column('driver', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###