"""update template to auto import geoalchemy2

Revision ID: f9c0b533370c
Revises: 810d3cae3574
Create Date: 2025-02-09 00:17:03.343066

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy import text
# revision identifiers, used by Alembic.
revision = 'f9c0b533370c'
down_revision = '810d3cae3574'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column(
    'driverlocation',
    sa.Column('location', Geography(geometry_type='POINT', srid=4326), nullable=False))
    op.drop_index('ix_driverlocation_h3_index', table_name='driverlocation')
    op.execute(
    text("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_driverlocation_location') THEN CREATE INDEX idx_driverlocation_location ON driverlocation USING gist (location); END IF; END $$;")
    )
    op.drop_column('driverlocation', 'h3_index')
    op.drop_column('driverlocation', 'longitude')
    op.drop_column('driverlocation', 'latitude')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driverlocation', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('driverlocation', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('driverlocation', sa.Column('h3_index', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('idx_driverlocation_location', table_name='driverlocation', postgresql_using='gist')
    op.create_index('ix_driverlocation_h3_index', 'driverlocation', ['h3_index'], unique=False)
    op.drop_column('driverlocation', 'location')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###