services:
  ambulance-finder-service:
    build:
      context: ..
      dockerfile: ./ambulance-finder-service/Dockerfile
      target: dev 
    container_name: ambulance-finder-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/ambulance-finder-service
      - /ambulance-finder-service/app/models
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ambulance-finder-service-test:
    build:
      context: ..
      dockerfile: ./ambulance-finder-service/Dockerfile
      target: test
    container_name: ambulance-finder-service-test
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RIDER_PASSWORD_1: ${RIDER_PASSWORD_1}
      RIDER_PASSWORD_2: ${RIDER_PASSWORD_2}
      DRIVER_PASSWORD_1: ${DRIVER_PASSWORD_1}
      DRIVER_PASSWORD_2: ${DRIVER_PASSWORD_2}
      DRIVER_PASSWORD_3: ${DRIVER_PASSWORD_3}
      DRIVER_PASSWORD_4: ${DRIVER_PASSWORD_4}
      DRIVER_PASSWORD_5: ${DRIVER_PASSWORD_5}
      DRIVER_PASSWORD_6: ${DRIVER_PASSWORD_6}

    volumes:
      - /ambulance-finder-service/app/models
      - /ambulance-finder-service/tests
      - ./:/ambulance-finder-service 
    command: >
      sh -c "pytest -v --cov=app --cov-report=xml:coverage.xml tests/unittest &&
           sed -i 's|/ambulance-finder-service/app|ambulance-finder-service/app|g' coverage.xml"