services:
  auth-service:
    build:
      context: ..
      dockerfile: ./auth-service/Dockerfile
      target: dev 
    container_name: auth-service
    ports:
      - "7000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/auth-service
      - /auth-service/app/models
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  auth-service-test:
    build:
      context: ..
      dockerfile: ./auth-service/Dockerfile
      target: test
    container_name: auth-service-test
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RIDER_PASSWORD_1: ${RIDER_PASSWORD_1}
      RIDER_PASSWORD_2: ${RIDER_PASSWORD_2}
      DRIVER_PASSWORD_1: ${DRIVER_PASSWORD_1}
      DRIVER_PASSWORD_2: ${DRIVER_PASSWORD_2}

    volumes:
      - /auth-service/app/models
      - /auth-service/tests
      - ./:/auth-service 
    command: >
      sh -c "pytest -v --cov=app --cov-report=xml:coverage.xml tests/unittest &&
           sed -i 's|/auth-service/app|auth-service/app|g' coverage.xml"