services:
  trip-service:
    build:
      context: ..
      dockerfile: ./trip-service/Dockerfile
      target: dev 
    container_name: trip-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /app/app/models
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  trip-service-test:
    build:
      context: ..
      dockerfile: ./trip-service/Dockerfile
      target: test
    container_name: trip-service-test
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RIDER_PASSWORD_1: ${RIDER_PASSWORD_1}
      RIDER_PASSWORD_2: ${RIDER_PASSWORD_2}
      DRIVER_PASSWORD_1: ${DRIVER_PASSWORD_1}
      DRIVER_PASSWORD_2: ${DRIVER_PASSWORD_2}

    volumes:
      - /app/app/models
      - /app/tests
      - ./:/app/  
    command: ["pytest", "-v", "--cov=app", "--cov-report=xml:/app/coverage-reports/coverage.xml", "tests/unittest"]