services:
  trip-service:
    build:
      context: ..
      dockerfile: ./trip-service/Dockerfile
    container_name: trip-service
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    volumes:
      - .:/app
      - /app/app/models
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  trip-service-test:
    build:
      context: ..
      dockerfile: ./trip-service/Dockerfile.test
    container_name: trip-service-test
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # - .:/app
      - /app/app/models
    command: ["pytest", "-v", "app/tests/unittest"]
