openapi: 3.0.0
info:
  title: Service API Documentation
  version: 1.0.0
  description: Comprehensive API documentation for Location, Ambulance Finder, Auth, Trip, and Coordinator WebSocket services.

paths:

  # Endpoints for Location Service

  /location/update:
    put:
      tags:
        - Location Service
      summary: Update driver location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
      responses:
        '200':
          description: Location updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
              
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /location/add:
    post:
      tags:
        - Location Service
      summary: Add driver location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                socket_id:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
      responses:
        '201':
          description: Location added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /location/remove:
    delete:
      tags:
        - Location Service
      summary: Remove driver location
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Location removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Location not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string


  # Endpoints for Ambulance Finder Service

  /ambulance/nearby:
    get:
      tags:
        - Ambulance Finder Service
      summary: Get nearby ambulances
      parameters:
        - name: radius
          in: query
          required: true
          schema:
            type: number
        - name: latitude
          in: query
          required: true
          schema:
            type: number
        - name: longitude
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: List of nearby ambulances
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    driver_id:
                      type: integer
                    name:
                      type: string
                    mobile:
                      type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  # Endpoints for Auth Service

  /auth/signup:
    post:
      tags:
        - Auth Service
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                password:
                  type: string
                user_type:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/login:
    post:
      tags:
        - Auth Service
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_or_email:
                  type: string
                password:
                  type: string
                user_type:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  id:
                    type: string
                  mobie:
                    type: string
                  role: 
                    type: string
                  email:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/token-validator:
    get:
      tags:
        - Auth Service
      summary: Token validation
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
        '401':
          description: Token is invalid or expired
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  # Endpoints for Trip Service

  /trip/new-request:
    post:
      tags:
        - Trip Service
      summary: Add trip request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rider_id:
                  type: integer
                pickup_loccation:
                  type: string
                destination:
                  type: string
      responses:
        '201':
          description: Trip request added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  req_id:
                    type: integer
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /trip/remove-request:
    delete:
      tags:
        - Trip Service
      summary: Remove trip request
      parameters:
        - name: req_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Trip request removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '404':
          description: Trip request not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /trip/engage-driver:
    post:
      tags:
        - Trip Service
      summary: Engage driver for a trip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                driver_id:
                  type: integer
                req_id:
                  type: integer
      responses:
        '201':
          description: Driver engaged successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '404':
          description: Trip or driver not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /trip/release-driver:
    delete:
      tags:
        - Trip Service
      summary: Release driver from a trip
      parameters:
        - name: driver_id
          in: query
          required: true
          schema:
            type: integer
      
      responses:
        '204':
          description: Driver released successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '404':
          description: Driver not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /trip/start:
    post:
      tags:
        - Trip Service
      summary: Add a trip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rider_id:
                  type: integer
                driver_id:
                  type: integer
                pickup_location:
                  type: string
                destination:
                  type: string
                fare:
                  type: number
                status:
                  type: string
      responses:
        '201':
          description: Trip added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  rider_id:
                    type: integer
                  driver_id:
                    type: integer
                  pickup_location:
                    type: string
                  destination:
                    type: string
                  fare:
                    type: number
                  status:
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /trip/update-status:
    put:
      tags:
        - Trip Service
      summary: Update trip status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: integer
                status:
                  type: string
      responses:
        '200':
          description: Trip status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
