name: Deploy Ambulance Finder Service

on:
  push:
    branches:
      - deploy/ambulance-finder-service


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ambulance-finder-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ambulance-finder-service:latest
          target: prod

      - name: Deploy to Render
        env:
          AMBULANCE_SERVICE_DEPLOY_HOOK_BASE: ${{ secrets.AMBULANCE_SERVICE_DEPLOY_HOOK }}
        run: |
        
          IMAGE_URL="docker.io%2Fimdadrakib%2Fambulance-finder-service:latest"

          DEPLOY_URL="${AMBULANCE_SERVICE_DEPLOY_HOOK_BASE}&imgURL=${IMAGE_URL}"

          curl -X POST "${DEPLOY_URL}"

          # For debugging
          echo "Deployment triggered with URL: ${DEPLOY_URL}"
        