name: Deploy Coordinator Service

on:
  push:
    branches:
      - deploy/coordinator-service 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./coordinator-service
          file: ./coordinator-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coordinator-service:latest
          target: prod

      - name: Deploy to Render
        env:
          COORDINATOR_SERVICE_DEPLOY_HOOK_BASE: ${{ secrets.COORDINATOR_SERVICE_DEPLOY_HOOK }}
        run: |
        
          IMAGE_URL="docker.io%2Fimdadrakib%2Fcoordinator-service:latest"

          DEPLOY_URL="${COORDINATOR_SERVICE_DEPLOY_HOOK_BASE}&imgURL=${IMAGE_URL}"

          curl -X POST "${DEPLOY_URL}"

          # For debugging
          echo "Deployment triggered with URL: ${DEPLOY_URL}"
        