name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Pylint on Changed Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pylint
        run: pip install pylint

      - name: Fetch latest main branch
        run: git fetch origin main

      - name: Detect Changes
        id: changed-files
        run: |
          echo "Checking for changes in PR..."
          
          # Get the list of changed files in the PR compared to main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Define an array of services
          SERVICES=("auth-service" "location-service" "ambulance-finder-service" "trip-service")

          # Loop through each service and check for changes
          for SERVICE in "${SERVICES[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^$SERVICE/app/"; then
              echo "SERVICE_CHANGED=$SERVICE" >> $GITHUB_ENV
              break
            fi
          done

          # Default to none if no service changed
          if [ -z "$SERVICE_CHANGED" ]; then
            echo "SERVICE_CHANGED=none" >> $GITHUB_ENV
          fi

      - name: Install dependencies and run Pylint
        if: env.SERVICE_CHANGED != 'none'
        run: |
          echo "Installing dependencies for ${{ env.SERVICE_CHANGED }}..."
          pip install -r ${{ env.SERVICE_CHANGED }}/requirements.txt
          echo "Running Pylint on ${{ env.SERVICE_CHANGED }}..."
          pylint --rcfile=.pylintrc ${{ env.SERVICE_CHANGED }}/app/**/*.py