name: Lint Check

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Run Pylint on Changed Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pylint
        run: pip install pylint

      - name: Fetch latest dev branch
        run: git fetch origin dev

      - name: Detect Changes
        id: changed-files
        run: |
          echo "Checking for changes in PR..."

          # Get the list of changed files in the PR compared to dev
          CHANGED_FILES=$(git diff --name-only origin/dev...HEAD)
          
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Detect if auth-service/app/ changed
          if echo "$CHANGED_FILES" | grep -q '^auth-service/app/'; then
            echo "AUTH_CHANGED=true" >> $GITHUB_ENV
          fi

          # Detect if location-service/app/ changed
          if echo "$CHANGED_FILES" | grep -q '^location-service/app/'; then
            echo "LOCATION_CHANGED=true" >> $GITHUB_ENV
          fi

          # Detect if ambulance-finder-service/app/ changed
          if echo "$CHANGED_FILES" | grep -q '^ambulance-finder-service/app/'; then
            echo "AMBULANCE_CHANGED=true" >> $GITHUB_ENV
          fi

          # Detect if trip-service/app/ changed
          if echo "$CHANGED_FILES" | grep -q '^trip-service/app/'; then
            echo "TRIP_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Install auth-service dependencies (if changed)
        if: env.AUTH_CHANGED == 'true'
        run: pip install -r auth-service/requirements.txt

      - name: Install location-service dependencies (if changed)
        if: env.LOCATION_CHANGED == 'true'
        run: pip install -r location-service/requirements.txt

      - name: Install ambulance-finder-service dependencies (if changed)
        if: env.AMBULANCE_CHANGED == 'true'
        run: pip install -r ambulance-finder-service/requirements.txt

      - name: Install trip-service dependencies (if changed)
        if: env.TRIP_CHANGED == 'true'
        run: pip install -r trip-service/requirements.txt

      - name: Run Pylint on auth-service/app/ (if changed)
        if: env.AUTH_CHANGED == 'true'
        run: pylint auth-service/app/**/*.py

      - name: Run Pylint on location-service/app/ (if changed)
        if: env.LOCATION_CHANGED == 'true'
        run: pylint location-service/app/**/*.py

      - name: Run Pylint on ambulance-finder-service/app/ (if changed)
        if: env.AMBULANCE_CHANGED == 'true'
        run: pylint ambulance-finder-service/app/**/*.py

      - name: Run Pylint on trip-service/app/ (if changed)
        if: env.TRIP_CHANGED == 'true'
        run: pylint trip-service/app/**/*.py
